# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: JavaCIwithMaven | 8 temurin

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        # distribution: 'corretto'
        distribution: temurin
        cache: maven
    # - name: Build with Maven
      # run: mvn clean verify -B package --file pom.xml
    - name: cov
      # run: mvn test cobertura:cobertura  --file pom.xml 
      run: mvn clean verify 
      
      # head -5 target/site/jacoco/jacoco.xml
     # grep -m 1 '<counter type="INSTRUCTION" missed="\(.*\)' target/site/jacoco/jacoco.xml > cov.cov
     
     # export cov=$(sed -n -e '/counter type=\"INSTRUCTION"\(.*\)\/>\"/p' target/site/jacoco/jacoco.xml)
    - name: commit coverage to README file
      run: |
         sed -n -e '/counter type=\"INSTRUCTION"\(.*\)\/>\"/p' target/site/jacoco/jacoco.xml > cov.cov
         cat cov.cov
    # - uses: actions/upload-artifact@v2
      # with:
        # name: latest-coverage
        # path: target/site/cobertura/coverage.xml

    # - uses: actions/checkout@v2

    # Add dependencies (libraries + build tools)
    # - name: copy coverage
      # run: |
        # cp target/site/cobertura/coverage.xml target/reload-quartz.xml
        
    # - uses: actions/download-artifact@v2
      # with:
        # name: latest-coverage
# TODO remove, take cov from xml
    # - name: cov report
      # uses: irongut/CodeCoverageSummary@v1.3.0 
      # with:
        # filename:  target/site/cobertura/coverage.xml
        # output: file
        # format: markdown
        # badge: true

      # grep '<coverage line-rate="\(.*\)' target/site/cobertura/coverage.xml | cut -c 24-27 > cov.cov
    # - name: commit coverage
      # run: |
         # head -5 target/site/cobertura/coverage.xml
         # grep -m 1 '<coverage line-rate="\(.*\)' target/site/cobertura/coverage.xml > cov.cov
         # cat cov.cov 
     # export cov="$(head -1 code-coverage-results.md)"
     # sed -i "s|\[!\[Coverage\ Status\]\(.*\)|$cov|" README.md
     # git config user.name silviuilie
     # git config user.email silviuilie@gmail.com
     # git add README.md
     # git commit -m "coverage update"
     # git push 
        
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
